server:
  port: 8088 # 项目启动的端口

spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  profiles:
    active: dev # 默认激活 dev 本地开发环境


mybatis:
  # MyBatis xml 配置文件路径
  mapper-locations: classpath:/mapper/**/*.xml

rate-limit:
  api:
    limit: 100 # 接口限流阈值

logging:
  level:
    com.zealsinger.user.relation.mapper: debug

mq-consumer: # MQ 消费者
  follow-unfollow: # 关注、取关
    rate-limit: 10 # 每秒限流阈值

    
