server:
  port: 8081 # 项目启动的端口


spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  profiles:
    active: dev # 默认激活 dev 本地开发环境

storage:
  type: aliyun # 对象存储类型

rate-limit:
  api:
    limit: 100 # 接口限流阈值


# minio
minio:
  endpoint: http://192.168.17.131:9000
  accessKey: zealsinger
  secretKey: zealsingerbook

#aliyun
aliyun:
  endpoint: oss-cn-hangzhou.aliyuncs.com
  accessKey: LTAI5tCdPAEnC9dbuMpPDJdn
  secretKey: 1JnCAJ7kBYXzrAE5gh8LDmuxKgQxvO
